CREATE TABLE IF NOT EXISTS proposals (
  id            SERIAL PRIMARY KEY,
  name          VARCHAR(255) NOT NULL,
  icon          VARCHAR(50),
  description   TEXT,
  tags          TEXT[],
  url_path      VARCHAR(255),
  client_name   VARCHAR(255),
  client_location VARCHAR(255),
  pitch_text    TEXT,
  deliverables  JSONB,
  investment    JSONB,
  launch_price  DECIMAL(10,2),
  monthly_fee   DECIMAL(10,2),
  whatsapp_link VARCHAR(500),
  demo_url      VARCHAR(500),
  status        VARCHAR(20) DEFAULT 'draft',
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW()
);
